require 'dotenv'

Dotenv.load(File.expand_path('../.env', __FILE__))

task :default => [:build]

desc 'Build the image'
task :build do
  sh <<-EOS
    rm -rf vendor/cookbooks
    bundle exec berks vendor vendor/cookbooks
    export PACKER_LOG="true"
    export PACKER_LOG_PATH="$PWD/packer.log"
    packer build -force -only=virtualbox-iso template.json
  EOS
end

desc 'Generate a Vagrantfile'
task :gen_vagrantfile, :box do |t, args|
  sh("sed -e 's/{{box}}/#{args.box}/g' Vagrantfile.template > Vagrantfile")
end
